services:
  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    ports:
      - "5173:5173"
    command: ["npm", "start"]
    volumes:
      - ./frontend:/app
      - /app/node_modules # Anonymous volume for node_modules
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    ports:
      - "8080:8080"
    command: ["go", "run", "main.go"]
    volumes:
      - ./backend:/app/data
      - db-data:/app/data # Mount the volume to the directory whereSQLite files will be stored
    environment:
      - GO_ENV=development

volumes:
    db-data:
