version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    ports:
      - "5173:5173" # Vite's default port
    volumes:
      - ./frontend:/app
      - /app/node_modules # Anonymous volume for node_modules
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev -- --host"

  backend:
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      #- /app/go/pkg/mod # Anonymous volume for Go modules

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.xonf:ro
    depends_on:
      - frontend
      - backend
