version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ../infastructure/docker/frontend.Dockerfile
    ports:
      - "5173:5173" # Vite's default port
    volumes:
      - ./frontend:/app
      - /app/node_modules # Anonymous volume for node_modules
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev -- --host"

backend:
  build:
    context: ./backend
    dockerfile: ../infrastructure/docker/backend.Dockerfile
  ports:
    - "8080:8080"
  volumes:
    - ./backend:/app
    - /app/go/pkg/mod # Anonymous volume for Go modules

nginx:
  image: nginx:alpine
  ports:
    - "80:80"
  volumes:
    - ./infrastructure/nginx/nginx.config:/etc/nginx/nginx.conf:ro
  depends_on:
    - frontend
    - backend
